### ISSUE TITLE
flask demo is not working

### ISSUE THREAD

**Issue by x0rzkov** [souravs17031999/Object-Detection-MobileNet-cv#1]
Hi @souravs17031999  ,

Hope you are all well !

I tried to run the flask demo but it is not working.

Is it possible to fix it ?

Thanks in advance for your insights and inputs on that issue.

Cheers,
X

**Comment by souravs17031999** [comment]
Please explain the steps you did to reproduce the problem on my side.

Thanks.

**Comment by x0rzkov** [comment]
no code to start the server
https://github.com/souravs17031999/Object-Detection-MobileNet-cv/blob/master/object_detect_flask/object.py

**Comment by souravs17031999** [comment]
Really sorry, i forgot to add the code to start the server.

Please check out the updated readme, getting started section now contains detailed steps to execute flask server solutions.

Thanks.

**Comment by souravs17031999** [comment]
I am closing the issue but if there is any problem, feel free to open the new issue again.

Thanks.
